Fix missing linebreaks in Zig mode
Force at least 3 non-numeric chars for generated variable names, fixes:
```
error: primitive integer type 'i0m4eaAuSWEi0A1Wm1pd6C9CQiagdqFb' has leading zero
```

Fix error coercing comptime strings.